/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.max.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Maxuser service. Represents a row in the &quot;max_user&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.max.model.impl.MaxuserModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.max.model.impl.MaxuserImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Maxuser
 * @generated
 */
@ProviderType
public interface MaxuserModel
	extends BaseModel<Maxuser>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a maxuser model instance should use the {@link Maxuser} interface instead.
	 */

	/**
	 * Returns the primary key of this maxuser.
	 *
	 * @return the primary key of this maxuser
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this maxuser.
	 *
	 * @param primaryKey the primary key of this maxuser
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this maxuser.
	 *
	 * @return the uuid of this maxuser
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this maxuser.
	 *
	 * @param uuid the uuid of this maxuser
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the max user ID of this maxuser.
	 *
	 * @return the max user ID of this maxuser
	 */
	public long getMaxUserId();

	/**
	 * Sets the max user ID of this maxuser.
	 *
	 * @param maxUserId the max user ID of this maxuser
	 */
	public void setMaxUserId(long maxUserId);

	/**
	 * Returns the max user uuid of this maxuser.
	 *
	 * @return the max user uuid of this maxuser
	 */
	public String getMaxUserUuid();

	/**
	 * Sets the max user uuid of this maxuser.
	 *
	 * @param maxUserUuid the max user uuid of this maxuser
	 */
	public void setMaxUserUuid(String maxUserUuid);

	/**
	 * Returns the group ID of this maxuser.
	 *
	 * @return the group ID of this maxuser
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this maxuser.
	 *
	 * @param groupId the group ID of this maxuser
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this maxuser.
	 *
	 * @return the company ID of this maxuser
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this maxuser.
	 *
	 * @param companyId the company ID of this maxuser
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this maxuser.
	 *
	 * @return the user ID of this maxuser
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this maxuser.
	 *
	 * @param userId the user ID of this maxuser
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this maxuser.
	 *
	 * @return the user uuid of this maxuser
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this maxuser.
	 *
	 * @param userUuid the user uuid of this maxuser
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this maxuser.
	 *
	 * @return the user name of this maxuser
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this maxuser.
	 *
	 * @param userName the user name of this maxuser
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this maxuser.
	 *
	 * @return the create date of this maxuser
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this maxuser.
	 *
	 * @param createDate the create date of this maxuser
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this maxuser.
	 *
	 * @return the modified date of this maxuser
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this maxuser.
	 *
	 * @param modifiedDate the modified date of this maxuser
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the max user first name of this maxuser.
	 *
	 * @return the max user first name of this maxuser
	 */
	@AutoEscape
	public String getMaxUserFirstName();

	/**
	 * Sets the max user first name of this maxuser.
	 *
	 * @param maxUserFirstName the max user first name of this maxuser
	 */
	public void setMaxUserFirstName(String maxUserFirstName);

	/**
	 * Returns the max user last name of this maxuser.
	 *
	 * @return the max user last name of this maxuser
	 */
	@AutoEscape
	public String getMaxUserLastName();

	/**
	 * Sets the max user last name of this maxuser.
	 *
	 * @param maxUserLastName the max user last name of this maxuser
	 */
	public void setMaxUserLastName(String maxUserLastName);

	/**
	 * Returns the max user contact number of this maxuser.
	 *
	 * @return the max user contact number of this maxuser
	 */
	@AutoEscape
	public String getMaxUserContactNumber();

	/**
	 * Sets the max user contact number of this maxuser.
	 *
	 * @param maxUserContactNumber the max user contact number of this maxuser
	 */
	public void setMaxUserContactNumber(String maxUserContactNumber);

	/**
	 * Returns the max user email ID of this maxuser.
	 *
	 * @return the max user email ID of this maxuser
	 */
	@AutoEscape
	public String getMaxUserEmailId();

	/**
	 * Sets the max user email ID of this maxuser.
	 *
	 * @param maxUserEmailId the max user email ID of this maxuser
	 */
	public void setMaxUserEmailId(String maxUserEmailId);

	/**
	 * Returns the max user date of birth of this maxuser.
	 *
	 * @return the max user date of birth of this maxuser
	 */
	@AutoEscape
	public String getMaxUserDateOfBirth();

	/**
	 * Sets the max user date of birth of this maxuser.
	 *
	 * @param maxUserDateOfBirth the max user date of birth of this maxuser
	 */
	public void setMaxUserDateOfBirth(String maxUserDateOfBirth);

	@Override
	public Maxuser cloneWithOriginalValues();

}