/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jio.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Plan service. Represents a row in the &quot;JIO_Plan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.jio.model.impl.PlanModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.jio.model.impl.PlanImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Plan
 * @generated
 */
@ProviderType
public interface PlanModel
	extends BaseModel<Plan>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a plan model instance should use the {@link Plan} interface instead.
	 */

	/**
	 * Returns the primary key of this plan.
	 *
	 * @return the primary key of this plan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this plan.
	 *
	 * @param primaryKey the primary key of this plan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this plan.
	 *
	 * @return the uuid of this plan
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this plan.
	 *
	 * @param uuid the uuid of this plan
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the plan ID of this plan.
	 *
	 * @return the plan ID of this plan
	 */
	public long getPlanId();

	/**
	 * Sets the plan ID of this plan.
	 *
	 * @param planId the plan ID of this plan
	 */
	public void setPlanId(long planId);

	/**
	 * Returns the group ID of this plan.
	 *
	 * @return the group ID of this plan
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this plan.
	 *
	 * @param groupId the group ID of this plan
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this plan.
	 *
	 * @return the company ID of this plan
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this plan.
	 *
	 * @param companyId the company ID of this plan
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this plan.
	 *
	 * @return the user ID of this plan
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this plan.
	 *
	 * @param userId the user ID of this plan
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this plan.
	 *
	 * @return the user uuid of this plan
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this plan.
	 *
	 * @param userUuid the user uuid of this plan
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this plan.
	 *
	 * @return the user name of this plan
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this plan.
	 *
	 * @param userName the user name of this plan
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this plan.
	 *
	 * @return the create date of this plan
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this plan.
	 *
	 * @param createDate the create date of this plan
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this plan.
	 *
	 * @return the modified date of this plan
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this plan.
	 *
	 * @param modifiedDate the modified date of this plan
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the price of this plan.
	 *
	 * @return the price of this plan
	 */
	@AutoEscape
	public String getPrice();

	/**
	 * Sets the price of this plan.
	 *
	 * @param price the price of this plan
	 */
	public void setPrice(String price);

	/**
	 * Returns the validity of this plan.
	 *
	 * @return the validity of this plan
	 */
	@AutoEscape
	public String getValidity();

	/**
	 * Sets the validity of this plan.
	 *
	 * @param validity the validity of this plan
	 */
	public void setValidity(String validity);

	/**
	 * Returns the internet data of this plan.
	 *
	 * @return the internet data of this plan
	 */
	@AutoEscape
	public String getInternetData();

	/**
	 * Sets the internet data of this plan.
	 *
	 * @param InternetData the internet data of this plan
	 */
	public void setInternetData(String InternetData);

	/**
	 * Returns the subscription of this plan.
	 *
	 * @return the subscription of this plan
	 */
	@AutoEscape
	public String getSubscription();

	/**
	 * Sets the subscription of this plan.
	 *
	 * @param subscription the subscription of this plan
	 */
	public void setSubscription(String subscription);

	/**
	 * Returns the plan name of this plan.
	 *
	 * @return the plan name of this plan
	 */
	@AutoEscape
	public String getPlanName();

	/**
	 * Sets the plan name of this plan.
	 *
	 * @param planName the plan name of this plan
	 */
	public void setPlanName(String planName);

	/**
	 * Returns the voice of this plan.
	 *
	 * @return the voice of this plan
	 */
	@AutoEscape
	public String getVoice();

	/**
	 * Sets the voice of this plan.
	 *
	 * @param voice the voice of this plan
	 */
	public void setVoice(String voice);

	/**
	 * Returns the sms of this plan.
	 *
	 * @return the sms of this plan
	 */
	@AutoEscape
	public String getSms();

	/**
	 * Sets the sms of this plan.
	 *
	 * @param sms the sms of this plan
	 */
	public void setSms(String sms);

	/**
	 * Returns the is5g enable of this plan.
	 *
	 * @return the is5g enable of this plan
	 */
	public Boolean getIs5GEnable();

	/**
	 * Sets the is5g enable of this plan.
	 *
	 * @param is5GEnable the is5g enable of this plan
	 */
	public void setIs5GEnable(Boolean is5GEnable);

	/**
	 * Returns the is plan active of this plan.
	 *
	 * @return the is plan active of this plan
	 */
	public Boolean getIsPlanActive();

	/**
	 * Sets the is plan active of this plan.
	 *
	 * @param isPlanActive the is plan active of this plan
	 */
	public void setIsPlanActive(Boolean isPlanActive);

	/**
	 * Returns the plan effective date of this plan.
	 *
	 * @return the plan effective date of this plan
	 */
	@AutoEscape
	public String getPlanEffectiveDate();

	/**
	 * Sets the plan effective date of this plan.
	 *
	 * @param planEffectiveDate the plan effective date of this plan
	 */
	public void setPlanEffectiveDate(String planEffectiveDate);

	/**
	 * Returns the plan termed date of this plan.
	 *
	 * @return the plan termed date of this plan
	 */
	@AutoEscape
	public String getPlanTermedDate();

	/**
	 * Sets the plan termed date of this plan.
	 *
	 * @param planTermedDate the plan termed date of this plan
	 */
	public void setPlanTermedDate(String planTermedDate);

	@Override
	public Plan cloneWithOriginalValues();

}